### ISSUE TITLE
Mixture of Versions 0.1.0 and 0.1.1-SNAPSHOT Packages

### ISSUE THREAD

**Issue by godanny86** [adobe/commerce-cif-connector#10]
### Expected Behaviour

When building the "all" project from the source I expect some consistency in versions of packages that get built. I.e everything in the project is a SNAPSHOT build or everything is a release.

### Actual Behaviour

When building the connector from master there seem to be inconsistencies in the versions that get created:

![image](https://user-images.githubusercontent.com/8974514/57492705-af0bbc00-7276-11e9-9de9-a78a0038ec7e.png)

Look at: https://github.com/adobe/commerce-cif-connector/blob/master/all/pom.xml

I can see versions of **0.1.2**, **0.1.1-SNAPSHOT**, AND **0.1.0**.  Is this intentional?

```xml
<parent>
        <groupId>com.adobe.commerce.cif</groupId>
        <artifactId>cif-connector-parent</artifactId>
        <version>0.1.2</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>
...
<modelVersion>4.0.0</modelVersion>
    <artifactId>cif-connector-all</artifactId>
    <version>0.1.1-SNAPSHOT</version>
    <packaging>content-package</packaging>
...
 <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>cif-connector-content</artifactId>
            <version>0.1.0</version>
            <type>zip</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>cif-virtual-catalog-content</artifactId>
            <version>0.1.0</version>
            <type>zip</type>
            <scope>provided</scope>
        </dependency>
```

#### Steps to Reproduce

1. clone the repo
2. checkout master branch
3. from the root directory perform: `mvn clean install -PautoInstallAll`

**Comment by mhaack** [comment]
Hi, @godanny86 yes this is intentional the master branch has snapshot versions of all packages & bundles. But you don't need to build this project if you just use it, you can get the released all package from https://github.com/adobe/commerce-cif-connector/releases.

We will add that to the readme. Building it is only needed if you work on the project or going to customize it.

**Comment by godanny86** [comment]
hi @mhaack I'm still a little confused. Yes I understand the master branch has snapshot versions of all packages & bundles... my point is that when you build on master it does not deploy all Snapshot versions, there is a mixture of snapshot and release packages.

 https://github.com/adobe/commerce-cif-connector/releases just has zips of the source files. A user still needs to build them in order to get an installable package to AEM:

![image](https://user-images.githubusercontent.com/8974514/57539042-76afc080-72fe-11e9-88ce-3f87fe4b5d9b.png)

**Comment by mhaack** [comment]
@godanny86 good point the release versions are on Maven Central, like described on the readme. See https://search.maven.org/search?q=com.adobe.commerce.cif we should add that to the readme. While this is transparent for developers using it as a dependency of their projects it might not be the first place to look to download a package directly.

**Comment by cjelger** [comment]
@godanny86 We cannot constantly release each little change, so yes we will have some SNAPSHOT dependencies between releases. Also the project is not meant to have consistent release versions, each module has its own release cycle. See the README:

> Important: do not trigger releases from the reactor (top-level) project because we release each module independently.

We are not doing any "reactor" releases, because this implies that a release triggers a release for each sub-module, even if it doesn't have any change. We don't want to do that, so yes the version numbers will diverge. It's not very important because the `all` package always has the "right" versions at any time.

**Comment by cjelger** [comment]
BTW, just use the "maven" badge/link on the main page to download the latest released `all` package.

**Comment by godanny86** [comment]
Thanks @cjelger for the clarification!
