### ISSUE TITLE
Disable cache for "CIF Catalog Magento GraphQL Configuration Factory" doesn't work

### ISSUE THREAD

**Issue by geertsmichael** [adobe/commerce-cif-connector#87]
### Expected Behaviour

When cache is disabled, that the CIF Virtual catalog & Product Console is still working.
I am doing tests in Magento and want to see them reflected faster in AEM. Therefore, locally I want to disable cache. 

I could only bypass caching, by configuring all values to in the CIF Catalog Magento GraphQL Configuration Factory OSGI config to "1".

### Actual Behaviour

When any of these checkboxes is disabled, the Product Console is not working anymore.

<img width="868" alt="Schermafbeelding 2020-01-24 om 07 08 57" src="https://user-images.githubusercontent.com/14930982/73048196-91b86580-3e78-11ea-9a09-0e115bee73b4.png">
(after changing this config, I had to restart the CIF Connector Bundle)

No categories or products will load anymore on this screen:
http://localhost:4502/libs/commerce/gui/content/products.html/var/commerce/products

### Reproduce Scenario (including but not limited to)

1. Disable on, some or all checkboxes for caching on the "CIF Catalog Magento GraphQL Configuration Factory" OSGI config
2. Restart the CIF Connector & CIF Virtual catalog bundle
3. Go to http://localhost:4502/libs/commerce/gui/content/products.html/var/commerce/products
4. Try to open a virtual catalog pointing to Magento

I need to mention that I have a Product binding for multiple StoreViews on a single Magento instance (also have 1 OSGI config for this environment, and I am re-using the "Project" on the Product Bind config.

#### Platform and Version
AEM 6.4.5
CIF Connector 0.7.1

**Comment by cjelger** [comment]
I cannot reproduce this issue: if I disable the 3 checkboxes in the config, I can still see products in http://localhost:4502/libs/commerce/gui/content/products.html/var/commerce/products. However, I also had to increase the HTTP connection timeout values in the GraphQL client config, because disabling caching puts more load on Magento and I had some exceptions in the logs due to timeouts. But once this is fixed, everything works fine.

Please check if this fixes your problem. Also when you open issues, it would help if you can check the AEM logs and include a stacktrace in case there is one in the logs.

**Comment by cjelger** [comment]
While working and testing #88, I managed to "reproduce" this issue when caching is disabled (I'm actually not 100% sure it's the same problem, but looks like it is). I'll fix this in the same PR as for #88.
